# Generated by Django 5.1.3 on 2024-11-26 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0002_alter_music_play_time_alter_music_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('practice_id', models.AutoField(primary_key=True, serialize=False)),
                ('practice_date', models.DateField()),
                ('practice_count', models.IntegerField()),
                ('total_practice_time', models.TimeField()),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice',
            },
        ),
    ]
