# Generated by Django 5.1.3 on 2024-11-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_rename_music_id_practice_music_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice',
            old_name='music',
            new_name='music_id',
        ),
        migrations.RenameField(
            model_name='practice',
            old_name='user',
            new_name='user_id',
        ),
    ]
