# Generated by Django 5.1.3 on 2024-11-27 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_rename_music_practice_music_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice',
            old_name='music_id',
            new_name='music',
        ),
        migrations.RenameField(
            model_name='practice',
            old_name='user_id',
            new_name='user',
        ),
    ]
