# Generated by Django 5.1.3 on 2024-11-27 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_album_name_alter_music_artist_and_more'),
        ('practice', '0005_remove_practice_practice_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPractice',
            fields=[
                ('month_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=7)),
                ('total_practice_count', models.IntegerField(default=0)),
                ('total_practice_time', models.TimeField()),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monthly_practice',
            },
        ),
    ]
