# Generated by Django 5.1.3 on 2024-11-27 02:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_album_name_alter_music_artist_and_more'),
        ('practice', '0006_monthlypractice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlypractice',
            unique_together={('month', 'music', 'user')},
        ),
    ]
