# Generated by Django 5.1.3 on 2024-11-27 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_rename_music_id_practice_music_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='practice_count',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='total_practice_time',
        ),
    ]
