# Generated by Django 5.1.3 on 2024-11-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_alter_monthlypractice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='practice_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='practice',
            name='practice_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
