# Generated by Django 5.1.3 on 2024-11-28 06:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_music_album_alter_music_artist'),
        ('practice', '0009_alter_practice_practice_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='practice',
            unique_together={('practice_date', 'music', 'user')},
        ),
    ]
