# Generated by Django 5.1.3 on 2024-11-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0017_remove_practice_practice_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='practice',
            unique_together=set(),
        ),
    ]
