# Generated by Django 5.1.3 on 2024-11-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0018_alter_practice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='practice_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practice',
            name='practice_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
