# Generated by Django 5.1.3 on 2024-11-28 14:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_artist_artist_alter_music_title'),
        ('practice', '0020_alter_practice_practice_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='practice',
            unique_together={('practice_date', 'music', 'user')},
        ),
    ]
