# Generated by Django 5.1.3 on 2024-11-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=50)),
                ('album_name', models.CharField(max_length=50)),
                ('album_cover', models.CharField(max_length=255)),
                ('play_time', models.IntegerField()),
                ('total_count', models.IntegerField()),
            ],
            options={
                'db_table': 'music',
            },
        ),
    ]
