# Generated by Django 5.1.3 on 2024-11-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='play_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
