# Generated by Django 5.1.3 on 2024-11-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_play_time_alter_music_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
