# Generated by Django 5.1.3 on 2024-11-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_music_album_alter_music_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
