# Generated by Django 5.1.3 on 2024-11-26 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 3, 16, 58, 26, 984014, tzinfo=datetime.timezone.utc)),
        ),
    ]
