# Generated by Django 5.1.3 on 2024-11-27 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 2, 18, 39, 760907, tzinfo=datetime.timezone.utc)),
        ),
    ]
