# Generated by Django 5.1.3 on 2024-11-27 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 14, 10, 22, 242859, tzinfo=datetime.timezone.utc)),
        ),
    ]
