# Generated by Django 5.1.3 on 2024-11-28 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 6, 49, 18, 642041, tzinfo=datetime.timezone.utc)),
        ),
    ]
