# Generated by Django 5.1.3 on 2024-11-28 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 7, 59, 11, 247327, tzinfo=datetime.timezone.utc)),
        ),
    ]
